# Generated by Django 3.2.7 on 2021-09-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='url',
        ),
    ]
